#!/usr/bin/env python3

import argparse
import collections
import sys
import os

# ANSI Colors
RED = "\033[91m"
RESET = "\033[0m"

# Constants
# The NTLM hash for an empty password (or sometimes disabled account depending on context)
EMPTY_HASH = "31d6cfe0d16ae931b73c59d7e0c089c0"

def get_args():
    parser = argparse.ArgumentParser(
        description="""
        [ NTLM Reuse Analyzer ]
        ------------------------------------------------------------------
        Parses output from impacket-secretsdump to identify password reuse.
        It groups users by shared hashes and highlights potential admin 
        accounts in RED based on naming conventions (adm, admin, da, etc).
        """,
        epilog="""
        Example Usage:
          python3 analyze_hashes.py -f domain_hashes.ntds
          python3 analyze_hashes.py -f domain_hashes.ntds --show-all
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument("-f", "--file", required=True, help="Path to the .ntds file generated by secretsdump")
    parser.add_argument("--include-empty", action="store_true", help="Include empty/disabled password hashes (Default: Hidden)")
    
    return parser.parse_args()

def is_target_user(full_username):
    """
    Checks if the username matches specific admin patterns.
    Handles 'DOMAIN\\user' format by splitting the string.
    """
    # Split domain to get the actual user part (e.g., "CONTOSO\\a.smith" -> "a.smith")
    if "\\" in full_username:
        user_part = full_username.split("\\")[-1]
    else:
        user_part = full_username

    user_lower = user_part.lower()

    # 1. Prefixes (Beginning of user)
    prefixes = ("a.", "adm.", "adm_", "admin", "da.", "da_")
    if user_lower.startswith(prefixes):
        return True

    # 2. Suffixes (End of user)
    suffixes = ("_adm", ".admin", "_admin", ".a", "_da", ".da")
    if user_lower.endswith(suffixes):
        return True
        
    return False

def analyze_hashes(filename, include_empty):
    hash_map = collections.defaultdict(list)
    
    if not os.path.exists(filename):
        print(f"{RED}[!] Error: File '{filename}' not found.{RESET}")
        sys.exit(1)

    try:
        with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                
                parts = line.split(':')
                # Check for basic secretsdump format: user:id:lm:nt:::
                if len(parts) < 4:
                    continue
                
                user = parts[0]
                nt_hash = parts[3].lower()
                
                # Logic to skip empty hashes unless requested
                if not include_empty and nt_hash == EMPTY_HASH:
                    continue
                    
                hash_map[nt_hash].append(user)

    except Exception as e:
        print(f"{RED}[!] Error reading file: {e}{RESET}")
        sys.exit(1)

    # Filter for hashes that appear more than once
    shared_hashes = {k: v for k, v in hash_map.items() if len(v) > 1}
    
    # Sort by number of users (descending)
    sorted_hashes = sorted(shared_hashes.items(), key=lambda item: len(item[1]), reverse=True)

    print(f"\n[-] Total unique hashes found: {len(hash_map)}")
    print(f"[-] Total shared hash groups:  {len(shared_hashes)}")
    if not include_empty:
        print("    (Empty/Disabled hashes hidden by default)")
    print("-" * 60)
    
    for nt_hash, users in sorted_hashes:
        # Determine color for the Count (High reuse = suspicious)
        count = len(users)
        
        # Colorize users if they match the admin patterns
        colored_users = []
        has_admin = False
        
        for u in users:
            if is_target_user(u):
                colored_users.append(f"{RED}{u}{RESET}")
                has_admin = True
            else:
                colored_users.append(u)
        
        # Print the block
        print(f"Hash:  {nt_hash}")
        print(f"Count: {count}")
        print(f"Users: {', '.join(colored_users)}")
        print("-" * 60)

if __name__ == "__main__":
    args = get_args()
    analyze_hashes(args.file, args.include_empty)
